### ISSUE TITLE
Tcl compile bug?

### ISSUE THREAD

**Issue by tahoupt** [AppliedLogicSystems/homebrew-als-prolog#1]
installation using homebrew fails with error:

```
In file included from ../../alsp_src/../tcltk_interface/common/tcl_interface.c:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/Current/Headers/tk.h:23:3: error: Tk 8.5 must be compiled with tcl.h from Tcl 8.5
#       error Tk 8.5 must be compiled with tcl.h from Tcl 8.5
        ^
1 error generated.
make[2]: *** [tcl_interface.o] Error 1
make[1]: *** [all] Error 2
make: *** [core] Error 2
```

I'm using:
OSX 10.11.2, 
Homebrew 0.9.9 (git revision fbc5fc; last commit 2016-04-04)
Xcode 7.2 (7C68)
Tck/Tk info patchlevel 8.5.9

**Comment by chuckhoupt** [comment]
I pushed a change to ALSProlog (@034c8316c675bf6595ac284faba201b8183479f5), which removed the problematic include path. Now `brew reinstalling als-prolog` should produce the following error:

```
In file included from ../../alsp_src/../tcltk_interface/common/tcl_interface.c:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found
#       include <X11/Xlib.h>
                ^
1 error generated.
```

If we're in sync, then I'll proceed to fix the issue in the formula.

**Comment by chuckhoupt** [comment]
Last comment was a false lead. We should check how the Tcl/Tk headers are linked. Here are the headers from my 10.11 SDK, are yours any different?

```
$ ls -l /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include | grep ' t[ck]'

lrwxr-xr-x    1 root  wheel       72 Sep 17  2015 tcl.h@ -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tcl.h
lrwxr-xr-x    1 root  wheel       77 Sep 17  2015 tclDecls.h@ -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclDecls.h
lrwxr-xr-x    1 root  wheel       81 Sep 17  2015 tclPlatDecls.h@ -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclPlatDecls.h
lrwxr-xr-x    1 root  wheel       79 Sep 17  2015 tclTomMath.h@ -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMath.h
lrwxr-xr-x    1 root  wheel       84 Sep 17  2015 tclTomMathDecls.h@ -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMathDecls.h
lrwxr-xr-x    1 root  wheel       70 Sep 17  2015 tk.h@ -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tk.h
lrwxr-xr-x    1 root  wheel       75 Sep 17  2015 tkDecls.h@ -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkDecls.h
lrwxr-xr-x    1 root  wheel       82 Sep 17  2015 tkIntXlibDecls.h@ -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkIntXlibDecls.h
lrwxr-xr-x    1 root  wheel       76 Sep 17  2015 tkMacOSX.h@ -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkMacOSX.h
lrwxr-xr-x    1 root  wheel       79 Sep 17  2015 tkPlatDecls.h@ -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkPlatDecls.h
```

**Comment by chuckhoupt** [comment]
I also checked in another change that might resolve the issue (@2cc6d3908451a32491fea1e9047101573152994f), so retry `brew reinstall als-prolog`

**Comment by tahoupt** [comment]
They look the same to me (but I didn't do a real diff)

Voyages:~ houpt$ ls -l /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include | grep t[ck]
drwxr-xr-x   18 root  wheel      612 Apr  3 21:13 dispatch
-rw-r--r--    1 root  wheel     3602 Oct 27 19:12 fnmatch.h
drwxr-xr-x    3 root  wheel      102 Apr  3 21:13 netkey
lrwxr-xr-x    1 root  wheel       72 Dec 16 23:41 tcl.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tcl.h
lrwxr-xr-x    1 root  wheel       77 Dec 16 23:41 tclDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclDecls.h
lrwxr-xr-x    1 root  wheel       81 Dec 16 23:41 tclPlatDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclPlatDecls.h
lrwxr-xr-x    1 root  wheel       79 Dec 16 23:41 tclTomMath.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMath.h
lrwxr-xr-x    1 root  wheel       84 Dec 16 23:41 tclTomMathDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMathDecls.h
lrwxr-xr-x    1 root  wheel       70 Dec 16 23:41 tk.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tk.h
lrwxr-xr-x    1 root  wheel       75 Dec 16 23:41 tkDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkDecls.h
lrwxr-xr-x    1 root  wheel       82 Dec 16 23:41 tkIntXlibDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkIntXlibDecls.h
lrwxr-xr-x    1 root  wheel       76 Dec 16 23:41 tkMacOSX.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkMacOSX.h
lrwxr-xr-x    1 root  wheel       79 Dec 16 23:41 tkPlatDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkPlatDecls.h

**Comment by tahoupt** [comment]
Still the same error.  It installed fine on my office imac a month or two ago, but my laptop is the one having problems...

Voyages:~ houpt$ brew reinstall als-prolog
==> Reinstalling appliedlogicsystems/als-prolog/als-prolog
==> Cloning https://github.com/AppliedLogicSystems/ALSProlog
Updating /Library/Caches/Homebrew/als-prolog--git
==> Checking out branch master
==> make standard
Last 15 lines from /Users/houpt/Library/Logs/Homebrew/als-prolog/01.make:
        alloc.o arith.o random.o bcinter.o bdb.o bdbg.o bgv.o bio.o bmeta.o bmisc.o bos.o bparser.o bpckg.o bsio.o bsystem.o built.o butil.o cinterf.o compile.o compmath.o cutmacro.o debugsys.o expand.o fatal.o fileio.o foreign.o fpbasis.o freeze.o gc.o gv.o index.o lexan.o lforeign.o loadfile.o main.o mapsym.o mem.o module.o parser.o pckgcoff.o pckgload.o pckgmake.o rinfo.o sig.o symtab.o varproc.o vprintf.o wdisp.o wintcode.o winter.o nopckg.o ieeemath.o pimain.o new_alspi.o engine.o relocate_code.o cexception.o cassert.o demo.o disassem.o icode1.o icode2.o wam.o unixio.o missing.o unix_engine.o unix_locate.o compat_glob.o -Wl,-no_pie
./alspro_b -q -b -obp -g "attach_image('libalspro.dylib')"
rm -f alsdir/builtins/_.obp
rm -f alsdir/library/_.obp
./alspro_b -q -b -obp ../../alsp_src/../als_dev/alsdev/ldr_alspro.pro -g 'save_image(alspro,[])'
clang -m32 -std=gnu99 -O0 -MMD -Wall -Wmissing-prototypes -Wwrite-strings -Wnested-externs -Wpointer-arith -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DGIT_VERSION= -I ../../alsp_src/port -I ../../alsp_src/unix -I ../../alsp_src/generic -I ../../alsp_src/smath  -DUNIX -DUNIX_DARWIN -DPORT  -c -o unix_alsdev.o ../../alsp_src/../als_dev/alsdev/unix_alsdev.c
clang -m32 -std=gnu99 -O0 -MMD -Wall -Wmissing-prototypes -Wwrite-strings -Wnested-externs -Wpointer-arith -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DGIT_VERSION= -I ../../alsp_src/port -I ../../alsp_src/unix -I ../../alsp_src/generic -I ../../alsp_src/smath  -DUNIX -DUNIX_DARWIN -DPORT  -c -o tcl_interface.o ../../alsp_src/../tcltk_interface/common/tcl_interface.c
In file included from ../../alsp_src/../tcltk_interface/common/tcl_interface.c:17:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tk.h:23:3: error: Tk 8.5 must be compiled with tcl.h from Tcl 8.5

# error Tk 8.5 must be compiled with tcl.h from Tcl 8.5

```
    ^
```

1 error generated.
make[2]: **\* [tcl_interface.o] Error 1
make[1]: **\* [all] Error 2
make: **\* [core] Error 2

**Comment by chuckhoupt** [comment]
Via synchronous com-channel, we determined that the problem was a 3rd party install of Tcl/Tk which added tcl.h/tk.h headers to /usr/local/include. Homebrew's build environment adds /usr/local/include as a system path which causes header mixups. Now the Formula removes the extra system include paths.

**Comment by chuckhoupt** [comment]
@tahoupt reports that local tcl/tk headers are still causing problems. We'll need to lock down the Homebrew build to *only* use sdk include paths.
